baseURL: 'https://shark-revenge.netlify.app/'
title: Shark Revenge
languageCode: en-us
defaultContentLanguage: en
paginate: '7'
theme: spectral
params:
  body_is_markdown: yes
  contact:
    address: 1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country
    body: Leave us a message.
    email: daehyunbouche@gmail.com
    enable: yes
    formspree_form_id: example_invalid
    phone: +49 (0) 030 000 000
    subject: New Submission!
    title: Contact us
  copyright: Vincent Bouché
  cta:
    body: Protection and conservation of marine wildlife by using traditional and modern tools. Taking in consideration the culture and tradition of human people. 
    enable: yes
    link:
      - href: '#'
        special: yes
        text: Contact us
      - href: '#'
        special: no
        text: Learn More
    title: Our mission
  description: Protection of marine wildlife using traditional and modern tools to maintain a healthy ecosystem
  fancyTitle: Ocean Research 
  menu:
    main:
      - title: Home
        url: /
      - title: About us
        url: /about us/
      - title: News
        url: /news/
      - title: Publications
        url: /publications/
      - title: Galery
        url: /galery/
      - title: Contact
        url: /contact/
  one:
    body: "Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend
      \ \r\nfringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.\r\n"
    enable: yes
    icon:
      - icon: fa-gem
        label: Lorem
        style: '1'
      - icon: fa-heart
        label: Ipsum
        style: '2'
      - icon: solid fa-code
        label: Dolor
        style: '3'
    title: Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep
      donec
  social:
    dribble: ''
    facebook: ''
    github: ''
    instagram: ''
    mastodon: ''
    twitter: ''
    youtube: ''
  startbuttonLink: '#'
  startbuttonText: Activate
  three:
    body: "Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend
      \ \r\nfringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.\r\n"
    enable: yes
    feature:
      - body: Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt
          nullam amet leo Aenean ligula consequat consequat.
        icon: fa-paper-plane
        title: Arcu accumsan
      - body: Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt
          nullam amet leo Aenean ligula consequat consequat.
        icon: solid fa-laptop
        title: Ac Augue Eget
      - body: Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt
          nullam amet leo Aenean ligula consequat consequat.
        icon: solid fa-code
        title: Foo bar
      - body: Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt
          nullam amet leo Aenean ligula consequat consequat.
        icon: solid fa-headphones-alt
        title: Baz kram
      - body: Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt
          nullam amet leo Aenean ligula consequat consequat.
        icon: fa-heart
        title: Some latin text
      - body: Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt
          nullam amet leo Aenean ligula consequat consequat.
        icon: fa-flag
        title: Nothing important
    title: Accumsan mus tortor nunc aliquet
  two:
    enable: yes
    section:
      - body: Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet.
          Mauris eleifend fringilla nullam aenean mi ligula.
        img: img/pic01.jpg
        img_alt: 'blurry background: white/grey'
        title: Magna primis lobortis<br />sed ullamcorper
      - body: Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet.
          Mauris eleifend fringilla nullam aenean mi ligula.
        img: img/pic02.jpg
        title: Tortor dolore feugiat<br />elementum magna
      - body: Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet.
          Mauris eleifend fringilla nullam aenean mi ligula.
        img: img/pic03.jpg
        title: Magna primis lobortis<br />sed ullamcorper
taxonomies:
  category: categories
  series: series
  tag: tags
languages:
  de:
    languageName: Deutsch
    weight: 10
  en:
    languageName: English
    weight: 0
  es:
    languageName: Français
    weight: 10
